### ISSUE TITLE
Issues Blocking MVP

### ISSUE THREAD

**Issue by aldmbmtl** [juno-fx/report#211]
These are issues that are actively blocking us from our MVP. These must be solved before we open up our Alpha.

- [x] juno-fx/hubble#202
- [x] juno-fx/hubble#201
- [x] juno-fx/hubble#200
- [x] juno-fx/hubble#204
